#! /usr/bin/make -f

image=httpd-techdayqr
tag=$(USER)-SNAPSHOT
name=$(image)-$(tag)
registry=docker.swift.com:5000
persistent=/var/lib/docker/persistent/$(name)

runargs=--publish-all \
	--restart=on-failure:5 

